Repository lucasgp147/Sistema-de-Judocas, pull requests merged in 2024-12, with the labels that each got.

#4 Create maven.yml
  .github/workflows/maven.yml
Labels: enhancement

#5 fix: form path
  pom.xml
Labels: bug

#6 maven changes
  .github/workflows/maven.yml
  pom.xml
Labels: enhancement, comission

#9 Feat/tests
  .classpath
  .project
  .vscode/settings.json
  lib/genesis/dist/genesis-annotation-jdk5-3.2.jar
  pom.xml
Labels: enhancement

#10 feat: add coverage for workflow
  .github/workflows/maven.yml
  pom.xml
Labels: enhancement

#33 feat: change tests page
  .github/workflows/maven.yml
  src/test/java/AppTest.java
  src/test/java/org/fpij/jitakyoei/model/ModelIntegrationTests.java
  src/test/java/org/fpij/jitakyoei/model/dao/AlunoDaoTest.java
Labels: code

#34 feat: change Ci name
  .github/workflows/maven.yml
Labels: enhancement

#35 Aluno.java UNITY TEST CASE
  src/test/java/AppTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/AlunoBeansTest.java
Labels: test case

#37 RG.java UNITY TEST CASE
  .github/workflows/maven.yml
  src/test/java/org/fpij/jitakyoei/model/beans/RGBeansTest.java
Labels: test case

#36 Filiado.java UNITY TEST CASE
  src/test/java/org/fpij/jitakyoei/model/beans/FiliadoBeansTest.java
Labels: test case

#40 Professor.java and ProfessorEntidade.java UNIT TEST CASE
  .classpath
  src/test/java/org/fpij/jitakyoei/model/beans/ProfessorBeansTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/ProfessorEntidadeTest.java
Labels: code, test case

#41 feat: add coverage images
  docs/coverage/coverage_aluno.png
  docs/coverage/coverage_filiado.png
  docs/coverage/coverage_professor.png
  docs/coverage/coverage_professor_entidade.png
  docs/coverage/coverage_rg.png
  docs/coverage/coverage_testado.png
  docs/coverage/coverage_total.png
  src/main/java/org/fpij/jitakyoei/model/beans/Professor.java
  src/test/java/org/fpij/jitakyoei/model/beans/AlunoBeansTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/FiliadoBeansTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/ProfessorBeansTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/ProfessorEntidadeTest.java
  src/test/java/org/fpij/jitakyoei/model/beans/RGBeansTest.java
Labels: documentation
